version: "3"
services:
  api-server:
    image: api-server
    hostname: server
    ports:
      - "5000:5000"
  react-app:
    image: react-app
    ports:
      - "3000:3000"
networks:
  mern-app:
    driver: bridge
