export const PRODUCT_PAYMENT_REQUEST = 'PRODUCT_PAYMENT_REQUEST';
export const PRODUCT_PAYMENT_SUCCESS = 'PRODUCT_PAYMENT_SUCCESS';
export const PRODUCT_PAYMENT_FAIL = 'PRODUCT_PAYMENT_FAIL';

export const PAYMENT_SAVE_REQUEST = 'PAYMENT_SAVE_REQUEST';
export const PAYMENT_SAVE_SUCCESS = 'PAYMENT_SAVE_SUCCESS';
export const PAYMENT_SAVE_FAIL = 'PAYMENT_SAVE_FAIL';

