export const PRODUCT_RECORD_REQUEST = 'PRODUCT_RECORD_REQUEST';
export const PRODUCT_RECORD_SUCCESS = 'PRODUCT_RECORD_SUCCESS';
export const PRODUCT_RECORD_FAIL = 'PRODUCT_RECORD_FAIL';
export const RECORD_SAVE_REQUEST = 'RECORD_SAVE_REQUEST';
export const RECORD_SAVE_SUCCESS = 'RECORD_SAVE_SUCCESS';
export const RECORD_SAVE_FAIL = 'RECORD_SAVE_FAIL';

